version: '3.8'

services:
  postgres:
    container_name: course
    image: postgres
    ports:
      - 5432:5432
    volumes:
      - ./src/main/resources/db/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=course